name: MiraiAuthenticator Test
on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  check:
    environment: AFDIAN
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Assemble
        run: ./gradlew assemble --scan

      - name: MiraiAuthenticatorTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.auth.MiraiAuthenticatorTest" --scan --info
        env:
          AFDIAN_USER_ID: ${{ secrets.AFDIAN_USER_ID }}
          AFDIAN_USER_TOKEN: ${{ secrets.AFDIAN_USER_TOKEN }}
